ktor {
    deployment {
        port = 8080
        watch = [ com.android.capstone.sereluna.backend ]
    }
    application {
        modules = [ com.android.capstone.sereluna.backend.ApplicationKt.module ]
    }
}

sereluna {
    geminiModel = "gemini-2.0-flash"
    cors {
        allowedHosts = "localhost:8080"
    }
}
